catering/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('article/', include('status.urls')),
    path('login/', include('login.urls')),
    path('menu/', include('menu.urls')),
    path('order/', include('order.urls')),
    path('feedback/', include('feedback.urls')),
]

feedback/urls.py
from django.urls import path
from feedback import views

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    path('menu_type/', views.menu_type, name='menu_type'),

]

homepage/urls.py
from django.urls import path
from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('qna/', views.qna, name='qna'),
    path('about-us/', views.about_us, name='about-us'),
    path('our-team/', views.our_team, name='our-team'),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

menu/urls.py
from django.urls import path
from menu import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu, name='menu'),
    path('request/', views.requestMenu, name='requestMenu'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order, name='order'),
]

status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.article, name='article'),
    path('satu/', views.status, name='status'),
    path('dua/', views.article_dua, name='article_dua'),
]

feedback/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    menu = models.CharField(max_length=50)
    message = models.TextField(blank = True)

    def __str__(self):
        return self.menu

homepage/models.py
from django.db import models

# Create your models here.
class Answer(models.Model):
    key = models.CharField(max_length=50)
    answer = models.CharField(max_length=200)

    def __str__(self):
        return self.key

login/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

# Create your models here.
class RequestMenu(models.Model):
    namaMakanan = models.CharField(max_length=50)
    kategoriMakanan = models.CharField(max_length=30)
    deskripsiMakanan = models.TextField()

order/models.py
from django.db import models

# Create your models here.

class FormPemesanan(models.Model):
	namaPemesan = models.CharField(max_length = 50, null="False", blank="False")
	pilihanMenu = models.CharField(max_length = 500, null="False", blank="False")
	alamatPengiriman = models.CharField(max_length = 80, null="False", blank="False")
	jenisPembayaran = models.CharField(max_length = 30, null="False", blank="False")
	nomorTelepon = models.IntegerField(default=0, null="False", blank="False")
	notes = models.TextField()

	def __str__(self):
		return self.namaPemesan

status/models.py
from django.db import models

class create_status(models.Model):
    statusfield = models.CharField(max_length=300)
    time = models.DateTimeField()

    def __str__(self):
        return self.statusfield

menu/forms.py
from django import forms

class RequestMenu(forms.Form):
    namaMakanan = forms.CharField(
        label="Nama Makanan"
        )
    kategoriMakanan = forms.CharField(
        label="Kategori Makanan"
        )
    deskripsiMakanan = forms.CharField(
        widget=forms.TextInput(),
        label="Deskripsi Makanan"
        )

order/forms.py
# from order import models
# from django import forms

# class FormPemesanan(forms.Form):
# 	namaPemesan = models.CharField(max_length = 50)
# 	pilihanMenu = models.CharField(max_length = 500)
# 	alamatPengiriman = models.CharField(max_length = 80)
# 	jenisPembayaran = models.CharField(max_length = 30)
# 	nomorTelepon = models.IntegerField(default=0)
# 	notes = models.TextField()

feedback/views.py
from django.shortcuts import render
from feedback.models import Feedback

# Create your views here.
def feedback(request):
    if request.method == 'POST':
        selected_menu = request.POST.get('menu_type')
        if selected_menu == 1:
            menu = "Salad"
        elif selected_menu == 2:
            menu = "Steak"
        else:
            menu = "Halibut"
        message = request.POST.get('feedback')

        feedback = Feedback(menu=menu, message=message)
        feedback.save()
        return render(request, 'feedback.html', {'answer' : 'Thank you for submitting'})
    else:
        return render(request, 'feedback.html')

def menu_type(request):
    return render(request, 'data.json')

homepage/views.py
from django.shortcuts import render
from homepage.models import Answer

# Create your views here.
def homepage(request):
    return render(request, 'Homepage.html')

def about_us(request):
    return render(request, 'About Us.html')

def our_team(request):
    return render(request, 'OurTeam-page.html')

def qna(request):
    if request.method == 'POST':
        splitted_keyword = request.POST.get('keyword').split(" ")
        answer = Answer.objects.all().get(key="notfound")
        for word in splitted_keyword:
            if len(Answer.objects.filter(key=word.lower()))==1:
                answer = Answer.objects.all().get(key=word)
        return render(request, 'QnA-page.html', {'answer' : answer})
    else:
        return render(request, 'QnA-page.html')

login/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

# Create your views here.

def login(request):
    if request.user.is_authenticated:
        return redirect('homepage:homepage')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(
                request, username=username, password=password
            )
            if user is not None:
                auth_login(request, user)
                request.session['username'] = user.first_name
                return redirect('homepage:homepage')
            else:
                return render(
                    request, 'login.html', {
                        'error' : 'invalid credential'
                    }
                )

    return render(request, 'login.html')

def logout(request):
    auth_logout(request)
    return redirect('homepage:homepage')

menu/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from . import models, forms


# Create your views here.
def menu(request):
    return render(request, "menupage.html")

def requestMenu(request):
    menu_baru = forms.RequestMenu()

    if request.method == "POST":
        models.RequestMenu.objects.create(
            namaMakanan = request.POST['namaMakanan'],
            kategoriMakanan = request.POST['kategoriMakanan'],
            deskripsiMakanan = request.POST['deskripsiMakanan'],
        )

        return HttpResponseRedirect("/menu/")

    context = {
        'menu_baru':menu_baru
    }

    return render(request, "request.html", context)

order/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import FormPemesanan

def order(request):

    if request.method == 'POST':

        nama_pemesan = request.POST.get('nama')
        pilihan_menu = request.POST.get('menu')
        alamat = request.POST.get('alamat')
        pembayaran = request.POST.get('pembayaran')
        no_telp = request.POST.get('telepon')
        notes = request.POST.get('notes')

        form_pemesanan = FormPemesanan(namaPemesan = nama_pemesan, pilihanMenu = pilihan_menu, alamatPengiriman = alamat, jenisPembayaran = pembayaran, nomorTelepon = no_telp, notes = notes)
        form_pemesanan.save()

        return render(request, 'Form Pemesanan.html')

    else:
        return render(request, 'Form Pemesanan.html')

status/views.py
from django.shortcuts import render, redirect
from .models import create_status
import datetime

def article(request):
    return render(request, 'artikel.html')

def article_dua(request):
    return render(request, 'artikel_dua.html')
    
def status(request):
    all_status=create_status.objects.all().order_by('time')
    context= {'all_status': all_status}
    if request.method == 'POST':
        status=create_status()
        status.statusfield=request.POST.get('statusfield')
        status.time=datetime.datetime.now()
        status.save()
        return render(request, 'status.html',context)
    else:
        return render(request, 'status.html',context)

feedback/templates/feedback.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cater.ing | Feedback</title>

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="{%static 'css/feedback-style.css' %}">
    <script src="{% static 'js/feedback_func.js' %}" type="text/javascript"></script>

</head>
<body>
    <div class="container mt-5 pt-5" id="feedback">
        <div class="d-flex flex-column text-center">
            <h1 class="mx">Feedback</h1>
            <h3>Tell us about your experience while ordering in catering</h3>
            <form id="form" method="POST">
                {% csrf_token %}
                <div class="form-group row justify-content-center">
                    <div class="col-6">
                        <select name="menu_type" id="menu_type" class="form-control input-lg my-3">
                            <option value="">Select menu</option>
                        </select>
                        <textarea class="form-control" rows="5" cols="70" name="feedback"></textarea>
                    </div>
                </div>
                <button type="submit" class="btn btn-info" id="submit">Submit</button>
            </form>
            
            <h3>{{ answer }}</h3>
            
        </div>
    </div>
</body>
</html>

homepage/templates/Homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home | Cater-ing</title>

    <link rel="stylesheet" href="{% static 'css/Homepage-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <div class="row">
        <div class="col-6"></div>
        <div class="col-6">
            <div class="container text-right homepage">

                {% if user.is_authenticated %}
                    <h1>Welcome! {{ request.user.username }}</h1>
                {% else %}
                    <h1>Welcome!</h1>
                {% endif %}
				
                <p> We provide delicious healthy food <br>
                    and send it to your doorstep!</p>
                <a href="{% url 'homepage:qna' %}"><button type="submit" class="btn btn-info">Explore</button></a>
                <a href="{% url 'homepage:about-us' %}"><button type="submit" class="btn btn-info">About Us</button></a>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{%static 'css/Navbar-style.css' %}"> 
    <link rel="stylesheet" href="{%static 'css/Navbar-style.css' %}">
    <link rel="stylesheet" href="{%static 'css/QnA-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}">
    <script src="{% static 'js/qna_func.js' %}" type="text/javascript"></script>

    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/Form-Pemesanan-style' %}"> -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
        <a class="navbar-brand header-title" href="#"><img src="{% static 'images/favicon.png' %}" width="50" height="50" alt="">
            <span class="header-title">Cater.ing</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:homepage'%}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'menu:menu' %}">Menu <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:qna'%}">Q&A<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'feedback:feedback'%}">Feedback<span class="sr-only">(current)</span></a>
                </li>
                {% endif %}
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'status:article'%}">Article <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <a href="{% url 'order:order' %}" class="btn btn-warning header-subtitle mx-3">Order Now</a> 
            <a href="{% url 'login:logout' %}" class="btn btn-warning header-subtitle">Logout</a>
            {% else %}
            <a href="{% url 'login:login' %}" class="btn btn-warning header-subtitle mx-3">Login</a>
            {% endif %}
        </div>    
    </nav>

    {% block content %}
    {% endblock %}
</body>

menu/templates/menupage.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title> Menu | Cater-ing </title>

    <link rel="stylesheet" href="{% static 'css/Navbar-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/Menu-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
          <a class="navbar-brand header-title" href="{% url 'homepage:homepage' %}"><img src="{% static 'images/favicon.png' %}" width="50" height="50" alt="">
              <span class="header-title">Cater.ing</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="{% url 'homepage:homepage' %}">Home <span class="sr-only"></span></a>
                  </li>
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="{% url 'menu:menu' %}">Menu <span class="sr-only"></span></a>
                  </li>
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="{% url 'homepage:qna' %}">Q&A<span class="sr-only"></span></a>
                  </li>
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="#">Article <span class="sr-only"></span></a>
                  </li>
              </ul>
              <a href="{% url 'order:order' %}" class="btn btn-warning header-subtitle">Order Now</a>
          </div>
      </nav>
    </div>

    <div class="menu row justify-content-center">
      <div class="card" align="center">
        <h2> Salad </h2>
        <img id="food" src="{% static 'images/salad.jpg' %}" alt="Oops, we can't load the image.">
        <p id='normaltext'> Ini adalah menu Salad terbaik <br>
        di Cater-ing. Menu salad ini <br>
        cocok untuk makanan besama keluarga <br>
        atau bersama rekan-rekan kerja. </p>
      </div>

      <div class="card" align="center">
        <h2> Steak </h2>
        <img id="food" src="{% static 'images/steak.jpeg' %}" alt="Oops, we can't load the image.">
        <p id='normaltext'> Ini adalah menu Steak kami. <br>
        Steak ini cukup untuk 20 kepala <br>
        Steak kami terbuat dari daging berkualitas. </p>
      </div>

      <div class="card" align="center">
        <h2> Halibut </h2>
        <img id="food" src="{% static 'images/halibut.jpg' %}" alt="Oops, we can't load the image.">
        <p id='normaltext'> Ini adalah menu Halibut kami. <br>
        Halibut merupakan ikan yang bernutrisi <br>
        dan kami menyediakan ikan terbaik. </p>
      </div>
    </div>

    <div class="but" align="center">
      <button type="button" class="btn btn-info"> Pesan sekarang! </button>
    </div>

    <br>

    <div class="but" align="center">
      <p> Ingin request makanan kesukaanmu? </p>
      <a href="{% url 'menu:requestMenu' %}" class="btn btn-info"> Klik disini! </a>
  </body>
</html>

menu/templates/request.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title> Request Menu | Cater-ing </title>

    <link rel="stylesheet" href="{% static 'css/Navbar-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/Menu-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
          <a class="navbar-brand header-title" href="{% url 'homepage:homepage' %}"><img src="{% static 'images/favicon.png' %}" width="50" height="50" alt="">
              <span class="header-title">Cater.ing</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="{% url 'homepage:homepage' %}">Home <span class="sr-only"></span></a>
                  </li>
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="{% url 'menu:menu' %}">Menu <span class="sr-only"></span></a>
                  </li>
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="{% url 'homepage:qna' %}">Q&A<span class="sr-only"></span></a>
                  </li>
                  <li class="nav-item active header-subtitle">
                      <a class="nav-link" href="#">Article <span class="sr-only"></span></a>
                  </li>
              </ul>
              <a href="{% url 'order:order' %}" class="btn btn-warning header-subtitle">Order Now</a>
          </div>
      </nav>
    </div>

    <div class="rectangle" align="center">
        <h1> Isi detail makananmu! </h1>
        <form method="post">
          {% csrf_token %}
          <table>
            <div class="form-group">
              <table>
                {{menu_baru.as_table}}
              </table>
              <br>
              <button class="btn btn-info" type="submit" name="button">Submit menu anda!</button>
            </div>
          </table>
        </form>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

status/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Poppins|Roboto&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{%static 'css/Navbar-style.css' %}"> 
    <link rel="stylesheet" href="{%static 'css/Navbar-style.css' %}">
    <link rel="stylesheet" href="{%static 'css/QnA-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}">
    <script src="{% static 'js/translate.js' %}" type="text/javascript"></script>

    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/Form-Pemesanan-style' %}"> -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
        <a class="navbar-brand header-title" href="#"><img src="{% static 'images/favicon.png' %}" width="50" height="50" alt="">
            <span class="header-title">Cater.ing</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:homepage'%}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'menu:menu' %}">Menu <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'homepage:qna'%}">Q&A<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'status:article'%}">Article <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <a href="{% url 'order:order' %}" class="btn btn-warning header-subtitle">Order Now</a> 
            {% else %}
            <a href="{% url 'login:login' %}" class="btn btn-warning header-subtitle">Login</a>
            {% endif %}
        </div>    

    </nav>

    {% block content %}
    {% endblock %}
</body>